---
title: "Como faz no R"
author: "Curso-R"
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
knit: "bookdown::render_book"
documentclass: report
bibliography: [assets/bibliography/book.bib, assets/bibliography/packages.bib]
biblio-style: apalike
site: bookdown::bookdown_site
description: "Livro da Curso-R."
---

```{r setup, include = FALSE}
# options(xtable.comment = FALSE)
knitr::opts_chunk$set(echo = FALSE, 
                      cache = TRUE, 
                      message = FALSE,
                      comment = FALSE, 
                      warning = FALSE, 
                      fig.height = 5, 
                      fig.width = 9)
# options(OutDec = ',')
# options(knitr.table.format = 'markdown')
```

```{r include_table, echo=FALSE}
library(tidyverse)
```

# Introdução

## Por quê ler esse livro {#objetivos}

## Organização 

# Análises 

# Tutoriais


```{r child="blogs/tutoriais/2018-07-03-tutorial-pipe.Rmd"}
```

```{r child="blogs/tutoriais/2017-02-20-o-que-e-um-grafico-estatistico.Rmd"}
```

```{r child="blogs/tutoriais/2017-04-08-glue.Rmd"}
```

```{r child="blogs/tutoriais/2017-02-21-markercluster.Rmd"}
```

# Modelagem 

```{r child="blogs/modelagem/2017-11-16-matrizes-esparsas.Rmd"}
```

```{r child="blogs/modelagem/2018-09-03-monty-hall.Rmd"}
```

```{r child="blogs/modelagem/2017-06-26-construindo-autoencoders.Rmd"}
```

```{r child="blogs/modelagem/2018-05-22-arvore-e-multicolinearidade.Rmd"}
```

```{r child="blogs/modelagem/2017-07-06-tidywoe.Rmd"}
```

```{r child="blogs/modelagem/2018-11-18-logistica-comp.Rmd"}
```

```{r child="blogs/modelagem/2017-04-10-sao-paulo.Rmd"}
```

```{r child="blogs/modelagem/2017-05-01-marvel-vs-dc.Rmd"}
```

```{r child="blogs/modelagem/2017-08-07-minimos-quadrados-restrito.Rmd"}
```

```{r child="blogs/modelagem/2017-09-18-bloom-filter.Rmd"}
```

```{r child="blogs/modelagem/2017-02-21-regressao-heterocedastica.Rmd"}
```

# Transformação

```{r child="blogs/transformacao/2017-11-23-union-sf.Rmd"}
```

```{r child="blogs/transformacao/2017-06-19-environments.Rmd"}
```

```{r child="blogs/transformacao/2017-07-24-janitor.Rmd"}
```

```{r child="blogs/transformacao/2017-06-17-skimr.Rmd"}
```

```{r child="blogs/transformacao/2017-09-07-pacote-miojo.Rmd"}
```

```{r child="blogs/transformacao/2019-02-10-pvec.Rmd"}
```

# Reflexões

```{r child="blogs/reflexoes/2017-02-16-manifesto-tidy.Rmd"}
```

```{r child="blogs/reflexoes/2017-08-17-eu-a-estatistica-e-o-R.Rmd"}
```

```{r child="blogs/reflexoes/2018-02-18-fluxo-scraping.Rmd"}
```

```{r child="blogs/reflexoes/2017-10-27-tidy-data-mixed-models.Rmd"}
```

`r if (knitr:::is_html_output()) '# Referências {-}'`

```{r include=FALSE}
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'assets/bibliography/packages.bib')
```










