---
date: "2017-08-17T23:26:00+03:00"
tags: ["estatística"]
categories: ["discussões", "r"]
banner: "img/banners/michael-kyle.jpg"
author: ["William"]
summary: "Neste post, iniciarei uma série com algumas reflexões sobre temas que orbitam o ensino de Estatística e a importância da programação na vida do estatístico."
---

## Eu, a Estatística e a programação

```{block, type='rmdtip', echo=TRUE}
Autor: William
```

```{block, type='rmdtip', echo=TRUE}
Dificuldade baixa
```

```{block, type='rmdimportant', echo=TRUE}
program
```

> --- Não sabia que nessa cidade a cada 20 minutos atropelam um homem? <br>
> --- Nossa! E como está o coitado?

O [episódio "Estatísticas"](https://youtu.be/UbRNe4OGXcQ?t=634) do Chaves foi o meu primeiro contato com o conceito de Estatística (pelo menos que eu possa me lembrar). Claro que naquela época, com 5 ou 6 anos, eu nunca imaginaria que seria essa a minha profissão. Assim como o Quico e o Chaves, eu não fazia muita ideia do que as "senhoras estatísticas"" eram e continuei sem saber de fato até entrar na graduação, em 2007.

Reassistindo o episódio, depois de mais de dez anos estudando a disciplina, me identifiquei bastante com a dificuldade que a Dona Florinda e o Professor Girafales têm para explicar o que são estatísticas, o que antes via apenas como uma escada para as piadas que constroem a cena.

Quando saio da minha bolha de colegas de faculdade e trabalho, percebo o quanto conceitos básicos de probabilidade e estatística são desconhecidos pela população, mesmo aqueles presentes no dia a dia.

Recentemente, lendo um comentário de um radialista sobre a derrota do São Paulo para o Coritiba, na rodada 18 do Campeonato Brasileiro, uma frase me chamou atenção.

> "Ao iniciar o jogo dessa quinta à noite, o Tricolor, de acordo com as estatísticas, tinha 1,78% de chances de vencer o Coritiba."

A tese do radialista é que a probabilidade dos quatro grandes times de São Paulo vencerem na mesma rodada do campeonato é de 1,78%, a frequência relativa desse evento na era de pontos corridos do Campeonato Brasileiro. Como o São Paulo foi o último grande a jogar e os outros três já haviam vencido, o pobre tricolor paulista teve suas chances reduzidas pelas estatísticas e acabou perdendo o jogo.

Essa interpretação com certeza pode ser refutada por vários motivos, mas o que mais me incomodou foi o desconhecimento de probabilidade condicional, ou simplesmente como novas informações modificam as probabilidades dos eventos.

Encucado, eu deixei uma resposta, cuja parte central é essa:

> Mesmo se considerássemos que a probabilidade dos 4 grandes de SP ganharem numa rodada não dependesse de fatores como a fase dos times, os adversários, o momento do campeonato etc., esse número, 1,78%, seria a probabilidade dos quatro ganharem antes da rodada começar. Dado que já sabemos que os outros três ganharam, e considerando que o resultado desses jogos não influenciam o jogo do SP, a probabilidade do evento em questão ocorrer passa a ser apenas a probabilidade do SP ganhar o jogo dele.

Em seguida, recebi alguns comentários de outros torcedores dizendo (jocosamente) que não tinham entendido nada do que escrevi. Comecei então a refletir sobre o assunto, pensando no quanto a minha explicação poderia estar confusa e de que forma poderia ter explicado melhor, no quanto as pessoas não costumam se esforçar para entender temas que elas não dominam e no quanto a falta de uma base matemática adequada atrapalha nessas horas.

Eu acredito que a Probabilidade e a Estatística são vítimas da onda do "é legal odiar Matemática", que muitas pessoas se orgulham de surfar. Crianças saem da escola com um conhecimento superficial dessas disciplinas (quando muito!), achando que é tudo uma questão de jogar dados, calcular médias e fazer gráficos. Comunicadores sofrem para interpretar os números de uma pesquisa e pesquisadores encaram a análise estatística como o grande vilão que os separa da publicação.

Felizmente, esse comportamento vem mudando, mesmo que a passos lentos. Profissionais estão buscando cursos de *data science* e programação, empresas estão promovendo cursos para qualificarem seus funcionários e o mercado para estatísticos continua um céu estrelado, tanto para analistas e programadores quanto para educadores.

Eu vejo essa mudança, e as pessoas ao meu redor também a veem. Mas o exemplo que citei acima me faz acreditar que preciso espiar fora da minha bolha.

Por isso, vou começar uma pequena série de posts, dando a minha opinião sobre algumas coisas que orbitam a educação estatística e a programação, com o objetivo de gerar reflexão e discussão sobre o assunto. A Estatística vem crescendo como carreira, o estatístico vem se tornando cada vez mais protagonista, e vejo esse momento como o ideal para melhorarmos a educação da nossa disciplina. 

Dividirei o texto nos seguintes tópicos:

- Por que amar a Estatística?
- Preconceitos no aprendizado
- Estatística e programação

Espero que esses posts possam contribuir para mostrarmos para mais gente a importância da Estatística e da Computação e por que amamos tanto trabalhar com essas ciências.

### Por que amar a estatística?

Escolher uma profissão, para quem tem esse privilégio, é uma das decisões mais importantes das nossas vidas. Aos 17, 18 anos, a imaturidade, o pouco auto-conhecimento e a falta de informação sobre as alternativas podem nos desviar da opção que nos vestiria melhor, um erro que muitas vezes nunca será reparado.

Às vezes, eu me pergunto o que levou amigos e conhecido a escolherem suas profissões na hora do vestibular. No meu caso, eu quase segui um caminho da "profissões da moda". O que me *impediu* de prestar Administração foi descobrir, na hora da inscrição, que era uma carreira da área de Humanas, não Exatas.

Sim, eu era bem perdido.

Na época, a segunda fase da FUVEST era diferente para cada área, e eu não tinha perspectiva nenhuma de ir bem se tivesse que fazer uma prova dissertativa de História e Geografia em vez de Matemática e Física, disciplinas que eu dominava muito mais. Por isso, após uma (muito breve) pesquisa na internet, fui convencido a prestar Estatística, e o que me convenceu foi a frase "[...] envolve bastante matemática e o mercado de trabalho é muito bom". Foi baseado nisso que eu tomei uma das decisões mais importantes da minha vida e era basicamente tudo o que eu sabia sobre a carreira quando comecei a graduação.

Prestar vestibular para Estatística foi um tiro no escuro tão certeiro que às vezes me pego pensando em destino e esoterismos desse tipo. Durante a graduação, conheci pessoas que não tiveram a mesma sorte e acabaram desistindo nos primeiros semestres, que são bem pesados na matemática. A primeira parte da informação que eu tinha sobre realmente estava certa, e o curso de Estatística pode assustar quem não estiver na pegada de provar vários teoremas. Mas, neste post, não quero falar sobre as dificuldades da escalada, mas sim sobre a vista ao se chegar ao topo.

Conforme fui conhecendo a Estatística, eu descobri que ela é a profissão mais nerd que existe[^nerd].  Eu sustento essa opinião porque a melhor definição de nerd que já escutei é "pessoa ama aprender" e, graças à Estatística, tenho a oportunidade de estudar *muita* coisa diferente.

[^nerd]: Se você ainda vê alguma conotação negativa na palavra *nerd*, mande as minha lembranças aos anos 90. 😉

Nesses dez anos como estatístico, já fiz análises na área de engenharia, finanças, educação, jornalismo, zoologia, farmácia, fisioterapia, medicina, psicologia, odontologia, educação física... e essas são apenas as que eu lembrei de cabeça. Estatística é parte essencial do método científico e está presente em todas as ciências. Pegar trabalhos novos para um estatístico nerd é extremamente motivante, porque não é apenas uma troca de tempo por dinheiro, é uma ótima chance para aprender coisas novas.  A Estatística te estimula a ser curioso e criativo, e isso é o que eu mais amo nela.

Outra coisa para se amar é o mercado de trabalho. 

A segunda parte da informação que eu tinha também estava correta: o mercado de trabalho para o estatístico é excelente! Não só pelo número de oportunidades, mas pela gama de lugares diferentes onde somos necessários. Não vou listar aqui porque é praticamente qualquer área. E sobre salários, como diria um professor do IME, dá para alimentar famílias. 

Apesar de ter sido um dos poucos dos meus colegas a não mergulhar de cabeça no mercado, já tive duas experiências. A primeira foi como estagiário em um banco, onde aprendi bastante sobre o que eu não queria fazer na vida. Tudo o que eu fazia era rodar modelos pré-estabelecidos para gerar relatórios pré-formatados. Tinha aprendido tanta coisa legal na graduação e não podia usar nada, o que me fazia sentir como um pássaro engaiolado. 

A segunda foi no Instituto Butantan, onde eu era o único estatístico ao lado de vários biólogos, farmacêuticos e veterinários. Foi uma ótima experiência, na qual conheci muita gente bacana e aprendi muita coisa de biologia, farmâcia e controle de qualidade. Trabalhar com pessoas diferentes de você, com outras formas de pensar, é outra parte legal de ser estatístico. O pessoal do Butantan me ensinou bastante, principalmente sobre como a ciência e a pesquisa funcionam na prática. Além disso, foi lá que nasceu o meu interesse em ensinar Estatística.

Bom, essa foi uma parte da história de como eu me apaixonei pela Estatística. Talvez eu não tenha acrescentado nada se você já compartilha desse sentimento, mas espero que esse texto chegue a pessoas que ainda estejam escolhendo sua profissão e jogue luz sobre essa alternativa. Essa é a hora de mudarmos gráficos como [esse](https://www.facebook.com/CONRE3/photos/a.244571322276453.56577.126677870732466/1471544826245757/?type=3&theater).

Resumindo:

- Estatística é *a* profissão para quem gosta de aprender.
- Um bom estatístico no mercado é uma criança com cartão de crédito numa loja de brinquedos.

No próximo post desta série, vou levantar um pouco de polêmica desabafando sobre alguns preconceitos de aprendizagem. Até breve!

### Preconceitos no aprendizado

Volta e meia eu escuto as famosas frases

```{r}
paste("Eu sou de", c("Humanas", "Exatas", "Biológicas"))
```

de alguém tentando justificar por que não vai fazer alguma coisa.

Muitas vezes, não passa de uma brincadeira na hora de dividir a conta do bar. Muitas outras, me soa como uma desculpa pronta para não encarar problemas complicados. Para mim, todo aprendizado é difícil, não acho que existe conhecimento de graça, então realmente importa se ele é de Humanas, Exatas ou Biológicas?

A divisão do conhecimento nessas três grandes áreas tem a sua importância organizacional, mas acaba motivando muita gente a criar limitações que não existem de verdade. Por que alguém de Exatas não conseguiria assimilar as ideias de um texto filosófico? Ou por que alguém de Biológicas não conseguiria aprender Cálculo?

Acredito que cada um de nós tem afinidade por uma das áreas e maior facilidade em estudar um tópico ou outro. Normal. Mas fico triste quando vejo pessoas inteligentes se diminuindo ao se declararem incapazes de aprender outras competências que não a delas. Sei que essa incapacidade não existe e enxergo apenas como uma forma sofisticada de dizer "Estou com preguiça".

Uma das belezas da Estatística é nos fazer perder esse preconceito\footnote{Ou medo. Ou preguiça. Na verdade, ainda temos preguiça, mas sabemos que é só preguiça.}. Por mais que tenhamos nossos gostos, descobrimos que não estamos presos ao domínio de apenas uma área. Nós trabalhamos com pessoas que pensam e aprendem de formas diferentes de nossa e construímos juntos pontes para trocarmos conhecimento. Ser estatístico é não ter medo de estudar, seja lá o que for.

Trazendo a reflexão aqui para o nosso mundinho, já ouvi muitas vezes colegas dizendo, principalmente na Graduação, que não usam o R porque ele é difícil ou porque não gostam de programar. A minha opinião sobre a primeira desculpa está nos parágrafos acima. Sobre a segunda, vou discutir no próximo e último post desta série: a relação entre Estatística e programação.

Resumindo a ópera: sempre vamos apanhar aprendendo, e vamos apanhar mais ainda quando não gostamos do que estamos estudando, mas cedo ou tarde, com a quantidade certa de esforço, o conhecimento dá as caras. 

E no bar, na hora de dividir a conta, o problema não é você ser de Humanas. O problema é a sua preguiça. :D

### Estatística e programação

Não importa a área de atuação, a maior parte do dia do estatístico é atrás do computador. E desse tempo, a maior parte é atrás de um (geralmente único) programa estatístico. 

Os principais programas hoje em dia permitem a execução das etapas essenciais de uma análise: interação com banco de dados, transformação, criação de visualizações e modelagem. Alguns vão além e auxiliam na comunicação dos resultados. Também é comum a existência de ambientes de programação, mesmo quando o programa é bem estruturado no *point and click*.

Eu considero a programação primordial para um estatístico. Ela nos dá a liberdade para sermos criativos, para não nos limitarmos em técnicas que alguém criou e todo mundo usa. Para mim, um estatístico que não sabe/gosta de programar é igual a um piloto que só dirige carro automático.

É por isso que o R é uma ferramenta tão incrível para se trabalhar. Ele pega a sua mão no momento em que você recebe a base de dados, estando ela arrumada ou não, e só solta depois da sua análise estar devidamente divulgada. Para cada problema, o R te fornece todas as peças e te deixa montar do jeito que quiser. E mesmo quando uma peça não existe, você mesmo pode criá-la ou pedir socorro para a comunidade mais que fantástica de erreiros pelo mundo. 

Claro que aprender a programar\footnote{Não só em R ou outra linguagem específica, mas aprender a lógica de programação.} é bem custoso. Para quem nunca foi familiar com a computação, vai ser um caminho bem tortuoso no início. Mas como discutimos no último post, não existe aprendizado de graça, e por mais que você não goste de estudar programação, é um investimento com retorno mais do que garantido.

### Wrap-up

Fazendo um resumão do que falamos até aqui, podemos enumerar os seguintes itens:

- A Estatística é uma disciplina fantástica, principalmente para quem gosta de aprender, e o mercado está bombando.

- Aprender Estatística é difícil, assim como todo conhecimento. O que vai limitar a sua capacidade de aprender é o quanto você vai conseguir dominar a sua preguiça de estudar.

- A Estatística e a programação andam lado a lado. O Estatístico que sabe programar tem muito mais poder para resolver problemas complicados.

- O R é o ambiente mais legal para trabalhar com Estatística. :D

É isso! Espero que possamos continuar discutindo o quanto é legal trabalhar com Estatística e que cada vez mais pessoas se interessem por esse caminho difícil, mas recompensador.

